Repository admiral-team/admiralui-ios, pull requests merged in 2022-05, with the labels that each got.

#180 [HOTFIX] - 5.0.1-dev
  AdmiralTheme.podspec
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineSliderTabs/UnderlineSliderTabs.swift
  Source/AdmiralUIKit/Classes/Components/Controls/Tab/SlideTab/UnderlineSliderTab/BaseUnderlineSegmentedControl.swift
  Source/AdmiralUIKit/Classes/Components/Views/TextFields/TextField/TextField.swift
  Source/AdmiralUIKit/Classes/Components/Views/Toolbar/Toolbar.swift
  version.json
Labels: bug

#182 [34] - Fixed layout of right textfield in SwiftUI DoubleInputRangeTextField
  Source/AdmiralSwiftUI/Classes/Components/Views/TextFields/Sliders/DoubleInputRangeTextField/DoubleInputRangeTextField.swift
Labels: bug

#183 [27] - Fixed grammatical error in Main Page
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/ItemSwiftUIRow/SwiftUIItem.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/MainViewController.swift
Labels: bug

#174 Feature/163 new underline tabs
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/UnderlineSliderTab/UnderlineSliderTabSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineSliderTabs/UnderlineSliderTabs.swift
  Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/StandardTab/StandardTab.swift
  Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/UnderlineSliderTab/UnderlineTab.swift
  Source/AdmiralUIKit/Classes/Components/Controls/Tab/SlideTab/UnderlineSliderTab/BaseUnderlineSegmentedControl.swift
  Source/AdmiralUIKit/Classes/Components/Controls/Tab/SlideTab/UnderlineSliderTab/UnderlineSegmentedControl/UnderlineTabsSegmentedControl.swift
Labels: bug

#186 [185] - Fix TextView
  Source/AdmiralUIKit/Classes/Components/Views/TextFields/TextView/TextView.swift
Labels: bug

#199 [194] - Spiner naming
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Spinner/SpinnerSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/MainViewController.swift
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/DoubleInputRangeTextField.DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/DoubleInputRangeTextField.DefaultTheme.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextView.Default-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextView.Disabled-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextView.Error-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextView.Normal-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextView.ReadOnly-Close.png
Labels: enhancement

#200 [196,197] - Themes constraints
  ExampleiOS/Source/Classes/UserStrories/Common/View/Cells/MenuListCell.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Common/Cells/MainTitleTableViewCell.swift
Labels: bug

#192 [RC] - 6.0.0
  ExampleiOS/Source/Classes/UserStrories/Chat/SwiftUI/Input/SwiftUIChatInputView.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/SwiftUI/Input/SwiftUIChatInputViewModel.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/Input/Cell/ChatMessageCell.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/Input/InputChatViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Common/View/Cells/MenuListCell.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Spinner/SpinnerSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Common/Cells/MainTitleTableViewCell.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/MainViewController.swift
  Source/AdmiralUIKit/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleView.swift
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/DoubleInputRangeTextField.DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/DoubleInputRangeTextField.DefaultTheme.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextView.Default-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextView.Disabled-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextView.Error-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextView.Normal-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextView.ReadOnly-Close.png
Labels: enhancement

#204 [202] - Added command script to build git_packages
  Scripts/build_git_packages.command
Labels: enhancement

#203 [165] - Fix SmallInformer arrow image
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Informers/SmallInformers/SmallInformersSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/InformersAndToasts/Informers/SmallInformers/SmallInformersViewController.swift
  Source/AdmiralSwiftUI/Classes/Components/Views/Informers/SmallInformer/SmallInformer.swift
  Source/AdmiralUIKit/Classes/Components/Views/Informers/SmallInformer/SmallInformer.swift
Labels: good first issue

#205 [168] - Disabled deleting default theme items
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Themes/ThemesViewController.swift
Labels: enhancement

#207 [113] - Fix naming in main demo
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/ItemSwiftUIRow/SwiftUIItem.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/BottomSheet/BottomSheetViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/MainViewController.swift
Labels: enhancement

#208 [108] - Fix Alerts&onboarding
  ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/Alert/AlertSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/ZeroScreen/ZeroScreenSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Alert&Onboarding/AlertViewController/AlertController.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Alert&Onboarding/ZeroScreen/ZeroScreenViewController.swift
  ExampleiOS/Source/Resources/Assets/Images.xcassets/Zeroscreen/Contents.json
  ExampleiOS/Source/Resources/Assets/Images.xcassets/Zeroscreen/Success.imageset/Contents.json
  ExampleiOS/Source/Resources/Assets/Images.xcassets/Zeroscreen/Success.imageset/Shape.pdf
  Source/AdmiralSwiftUI/Classes/Components/Views/ZeroScreen/ZeroScreenView.swift
  Source/AdmiralUIKit/Classes/Components/Views/ZeroScreen/ZeroScreenView.swift
Labels: enhancement

#212 [169] - Set Headers of State in Demo TextFields
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextFields/TextField/DoubleTextField/DoubleTextFieldSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextFields/TextField/PinCodeTextFieldView/PinCodeTextFieldSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextFields/TextField/Standard/StandardTextFieldSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/TextFields/Double/DoubleTextFieldViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/TextFields/Pincode/PinCodeViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/TextFields/Standard/StandardVSIcon/StandardVSIconMenuViewController.swift
Labels: bug

#209 [164] - Added leading label to DoubleTextRangeTextField Slider
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextFields/TextField/InputRangeTextField/InputRangeTextFieldSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/TextFields/Slider/SliderViewController.swift
  Source/AdmiralSwiftUI/Classes/Components/Views/TextFields/Sliders/DoubleInputRangeTextField/DoubleInputRangeTextField.swift
  Source/AdmiralSwiftUI/Classes/Components/Views/TextFields/Sliders/InputRangeTextField/InputRangeTextField.swift
  Source/AdmiralUIKit/Classes/Components/Views/TextFields/InputRangeTextField/InputRangeTextField.swift
Labels: enhancement

#210 [103] - Added Badge for OutlineSliderTabs
  ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/Logo/LogoTabSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/OutlineSliderTab/OutlineSliderTabSwiftUITab.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/Standard/StandardTabSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/UnderlineSliderTab/UnderlineSliderTabSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/LogoTabs/LogoTabsViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/OutlineSliderTabs/OutlineSliderTabsViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/StandardTabs/StandardTabsViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineSliderTabs/UnderlineSliderTabs.swift
  ExampleiOS/Source/Resources/Assets/Images.xcassets/Card/applePay.imageset/Contents.json
  ExampleiOS/Source/Resources/Assets/Images.xcassets/Card/applePay.imageset/applePay.svg
  ExampleiOS/Source/Resources/Assets/Images.xcassets/Card/googlePay.imageset/Contents.json
  ExampleiOS/Source/Resources/Assets/Images.xcassets/Card/googlePay.imageset/googlePay.svg
  Source/AdmiralUIKit/Classes/Components/Controls/Tab/SlideTab/OutlineSliderTab/OutlineSliderSegmentedControl/OutlineSliderCollectionViewCell.swift
  Source/AdmiralUIKit/Classes/Components/Controls/Tab/SlideTab/OutlineSliderTab/OutlineSliderSegmentedControl/OutlineSliderScheme.swift
  Source/AdmiralUIKit/Classes/Components/Controls/Tab/SlideTab/OutlineSliderTab/OutlineSliderSegmentedControl/OutlineSliderSegmentedControl.swift
  Source/AdmiralUIKit/Classes/Components/Views/Badge/Badge.swift
  Source/AdmiralUIKit/Classes/Components/Views/Badge/BadgeScheme.swift
Labels: enhancement

#235 [222] - Fix text toolbar
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Toolbar/ToolbarViewController.swift
Labels: bug

#236 [220] - Desable scroll bar
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/Logo/LogoTabSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/Standard/StandardTabSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/TabsSwiftUIView.swift
Labels: bug

#234 [224] - Fix animation duration
  Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/LogoTab/LogoTab.swift
Labels: bug

#240 [237] - Add certificates and profiles
  AdmiralUI.xcodeproj/project.pbxproj
  ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/ActionBarViewSecondary.DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/ActionBarViewSecondary.DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/CalendarView.Horizontal-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/CalendarView.Horizontal-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/DoubleInputRangeTextField.DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/DoubleInputRangeTextField.DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SecurityTextField.DefaultStateDarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SecurityTextField.DefaultStateDefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SecurityTextField.DisabledStateDarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SecurityTextField.DisabledStateDefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SecurityTextField.ErrorStateDarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SecurityTextField.ErrorStateDefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SecurityTextField.NormalStateDarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SecurityTextField.NormalStateDefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SecurityTextField.ReadOnlyStateDarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SecurityTextField.ReadOnlyStateDefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.AttentionBottom-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.AttentionBottom-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.AttentionTop-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.AttentionTop-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.DefaultBottom-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.DefaultBottom-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.DefaultTop-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.DefaultTop-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.ErrorBottom-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.ErrorBottom-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.ErrorTop-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.ErrorTop-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.SuccessBottom-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.SuccessBottom-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.SuccessTop-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/SmallInformer.SuccessTop-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/TextView.Disabled-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/TextView.Disabled-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/TextView.Error-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/TextView.Error-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/TextView.Normal-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/TextView.Normal-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/TextView.ReadOnly-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/TextView.ReadOnly-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/ToastView.DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/ToastView.DefaultTheme.png
  Tests/AdmiralSwiftUITests/SnapshotTests/Views/Cells/ActionBarCell/ActionBarViewSnapshotTests.swift
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/ChatBubbleView.Default.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/ChatBubbleView.Error.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/ProgressView.AccentLoading.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/UploadImageGridView.Loading-Six.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/testZeroScreen.DarkTheme.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/testZeroScreen.DefaultTheme.png
Labels: enhancement
