Repository admiral-team/admiralui-ios, pull requests merged in 2022-04, with the labels that each got.

#66 [56] - Added Small Badges Style - Added to Demo
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ios.yml
  ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Badges/BadgesItem.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Badges/BadgesSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Badges/Normal/NormalBadgesSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Badges/Normal/NormalBadgesViewModel.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Badges/Small/SmallBadgesSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Badges/Small/SmallBadgesViewModel.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Badges/BadgesViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Badges/BagesViewModel.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Badges/Cells/BadgeCellView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Badges/Normal/BadgesNormalViewContoller.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Badges/Normal/BadgesNormalViewModel.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Badges/Small/BadgesSmallViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Badges/Small/BadgesSmallViewModel.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Badges/View/BadgeCellView.swift
  README.md
  Source/AdmiralSwiftUI/Classes/Components/Views/Badge/BadgeView.swift
  Source/AdmiralSwiftUI/Classes/Components/Views/Chat/UploadFIleView/Document/Group/UploadDocumentGrid.swift
  Source/AdmiralUIKit/Classes/Components/Views/Badge/Badge.swift
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/BadgeView.AdditionalStyle-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/BadgeView.AdditionalStyle-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/BadgeView.AttentionStyle-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/BadgeView.AttentionStyle-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/BadgeView.DefaultStyle-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/BadgeView.DefaultStyle-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/BadgeView.ErrorStyle-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/BadgeView.ErrorStyle-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/BadgeView.NaturalStyle-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/BadgeView.NaturalStyle-DefaultTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/BadgeView.SuccessStyle-DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/BadgeView.SuccessStyle-DefaultTheme.png
  Tests/AdmiralSwiftUITests/SnapshotTests/Views/BadgeView/BadgeViewSnapshotTests.swift
  fastlane/Fastfile
  fastlane/build_info.rb
  fastlane/go_scripts/buildInfo.go
  fastlane/go_scripts/issues/createIssueComment.go
  fastlane/go_scripts/main.go
Labels: enhancement

#64 [64] - Fix content trailing view.
  Source/AdmiralSwiftUI/Classes/Components/Views/TextFields/TextView/TextView.swift
Labels: bug

#94 [12] - Fixed theme button layout problems in UIKit&SwiftUI
  ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
  ExampleiOS/Source/Classes/UserStrories/Common/View/ThemeSwitchView/ThemeSwitchView.swift
  ExampleiOS/Source/Classes/UserStrories/Common/View/ThemeSwitchView/ThemeSwitchViewCoordinator.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/CustomSwiftUIViewModel.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/ItemSwiftUIRow/ItemSwiftUIRowScheme.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/ItemSwiftUIRow/SwiftUIItem.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/NavigationContentView/NavigationContentView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/NavigationContentView/NavigationContentViewScheme.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/Representable/ThemeSwitchView/ThemeSwitchButton/ThemeSwitchButtonScheme.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/Representable/ThemeSwitchView/ThemeSwitchButton/ThemeSwitchButtonStyle.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/Representable/ThemeSwitchView/ThemeSwitchSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/Representable/ThemeSwitchView/ThemeSwitchViewRepresentable.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/Representable/ThemeSwitchView/ThemeSwitchViewScheme.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/SwiftUIContentViewScheme.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/ThemeSwitchSwiftUIView.swift
Labels: bug

#96 [28] - Chat Status Read
  ExampleiOS/Source/Classes/UserStrories/Chat/SwiftUI/Input/SwiftUIChatInputViewModel.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/Input/InputChatViewModel.swift
Labels: bug

#130 [111] - Added ErrorView to TextOperation
  ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
  ExampleiOS/Source/Classes/UserStrories/Chat/SwiftUI/TextOperation/SwiftUITextOperationViewModel.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/Input/Cell/ChatMessageCell.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/TextMessage/TextMessageViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/TextMessage/TextMessageViewModel.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/TextOperation/Cell/TextOperationCell.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/TextOperation/TextOperationViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/TextOperation/TextOperationViewModel.swift
  Source/AdmiralUIKit/Classes/Components/Views/Chat/TextOperation/TextOperationView.swift
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextOperation.Error.png
  Tests/AdmiralUIKitTests/SnapshotTests/Views/Chat/TextOperation/TextOperationTest.swift
Labels: bug

#132 [115] - Add spinner to Demo in SwiftUI
  ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/SwiftUIController.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Spinner/SpinnerSwiftUIView.swift
  Source/AdmiralSwiftUI/Classes/Components/Views/ActivityIndicator/ActivityIndicator.swift
Labels: bug

#129 [6] - Remove empty icons
  Source/AdmiralUIResources/Classes/CoreFoundation/Assets/Assets.swift
  Source/AdmiralUIResources/Resources/Assets/Images.xcassets/Redact/Outline/Contents.json
  Source/AdmiralUIResources/Resources/Assets/Images.xcassets/Redact/Outline/chartBarOutline.imageset/Contents.json
  Source/AdmiralUIResources/Resources/Assets/Images.xcassets/Redact/Outline/chartTrendingOutline.imageset/Contents.json
Labels: bug

#131 [118] - SwiftUI zeroscreen demo
  ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/AlertOnboardingSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/ZeroScreen/ZeroScreenSwiftUIView.swift
  Source/AdmiralSwiftUI/Classes/Components/Views/ZeroScreen/ZeroScreenView.swift
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/ZeroScreen.DarkTheme.png
  Tests/AdmiralSwiftUITests/Snapshot/__Snapshots__/Snapshots/ZeroScreen.DefaultTheme.png
Labels: enhancement

#144 [136] - Added Release Documentation
  Documentation/ReleaseCycle.md
Labels: documentation

#146 [29] - Fix text fields
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/TextFields/Slider/SliderViewController.swift
  Source/AdmiralUIKit/Classes/Components/Views/TextFields/Common/TextInputDecorationView.swift
  Source/AdmiralUIKit/Classes/Components/Views/TextFields/DoubleInputRangeTextField/DoubleInputRangeTextField.swift
  Source/AdmiralUIKit/Classes/Components/Views/TextFields/TextField/TextField.swift
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.Default-FixedFirst.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.Default-FixedSecond.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.Default-Ratio.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.Disabled-FixedFirst.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.Disabled-FixedSecond.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.Disabled-Ratio.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.Error-FixedFirst.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.Error-FixedSecond.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.Error-Ratio.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.Normal-FixedFirst.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.Normal-FixedSecond.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.Normal-Ratio.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.ReadOnly-FixedFirst.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.ReadOnly-FixedSecond.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/DoubleTextField.ReadOnly-Ratio.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/InputRangeTextField.Disabled-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/InputRangeTextField.Error-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/InputRangeTextField.Normal-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/InputRangeTextField.ReadOnly-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextField.Default-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextField.Disabled-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextField.Error-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextField.Normal-Close.png
  Tests/AdmiralUIKitTests/Snapshot/__Snapshots__/Snapshots/TextField.ReadOnly-Close.png
Labels: bug

#145 [127] - Disable textfield paste
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextFields/TextField/Standard/StandardTextFieldSwiftUIView.swift
  Examples/ExampleSPM/ExampleSPM.xcodeproj/project.pbxproj
  Examples/ExampleSPM/ExampleSPM.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Examples/ExampleSPM/ExampleSPM.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Examples/ExampleSPM/ExampleSPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Examples/ExampleSPM/ExampleSPM.xcodeproj/xcshareddata/xcschemes/ExampleSPM-Release.xcscheme
  Examples/ExampleSPM/ExampleSPM.xcodeproj/xcshareddata/xcschemes/ExampleSPM.xcscheme
  Examples/ExampleSPM/ExampleSPM/Assets.xcassets/AccentColor.colorset/Contents.json
  Examples/ExampleSPM/ExampleSPM/Assets.xcassets/AppIcon.appiconset/Contents.json
  Examples/ExampleSPM/ExampleSPM/Assets.xcassets/Contents.json
  Examples/ExampleSPM/ExampleSPM/ContentView.swift
  Examples/ExampleSPM/ExampleSPM/ExampleSPMApp.swift
  Examples/ExampleSPM/ExampleSPM/Info.plist
  Examples/ExampleSPM/ExampleSPM/Preview Content/Preview Assets.xcassets/Contents.json
  Source/AdmiralSwiftUI/Classes/Components/Views/Chat/ChatInput/ChatInput.swift
  Source/AdmiralSwiftUI/Classes/Components/Views/TextFields/BankCardTextField/BankCardTextField.swift
  Source/AdmiralSwiftUI/Classes/Components/Views/TextFields/OTPTextField/OTPTextField.swift
  Source/AdmiralSwiftUI/Classes/Components/Views/TextFields/SecureTextField/SecurityTextField.swift
  Source/AdmiralSwiftUI/Classes/Components/Views/TextFields/TextField/StandardTextField.swift
  Source/AdmiralSwiftUI/Classes/Components/Views/TextFields/TextView/TextView.swift
  Source/AdmiralSwiftUI/Classes/CoreFoundation/UITextField/ResponderUITextField.swift
  Source/AdmiralSwiftUI/Classes/CoreFoundation/UITextField/UIKitTextField.swift
  Source/AdmiralSwiftUI/Classes/CoreFoundation/UITextView/ResponderUITextView.swift
  Source/AdmiralSwiftUI/Classes/CoreFoundation/UITextView/UIKitTextView.swift
Labels: enhancement

#148 [70] - Hide scroll bars
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/Input/InputChatViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/TextMessage/TextMessageViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/TextOperation/TextOperationViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/UploadingFile/UploadingFileViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/UploadingImage/UploadingImageViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Common/ViewController/BaseTableViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Common/ViewController/MenuListViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Common/ViewController/ScrollViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Info/ContactsViewController/ContactsViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Info/FAQViewController/FAQViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Info/InfoViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Calendar/CalendarsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/ActionBar/Default/ActionBarSwiftUIViewDefault.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/ActionBar/Secondary/ActionBarSwiftUIViewSecondary.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/BaseCell/BaseCellSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/BaseCell/LeadingComponents/LeadingComponentsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/BaseCell/TralingComponents/TralingComponentsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/CellsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/ImageBaseCell/LableComponents/ImageLableComponentsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/TextBaseCell/TextBaseCellSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/TitleBaseCell/Primary/PrimaryTitleBaseCellSwiftUI.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/TitleBaseCell/Secondary/SecondaryTitleBaseCellSwiftUI.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/TitleBaseCell/TitleBaseCellSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Currency/CurrencySwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Informers/BigInformers/BigInformersSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Informers/InformersSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Informers/SmallInformers/SmallInformersSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/InformersAndToastsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Notifications /ActionNotification/ActionNotificationSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Notifications /NotificationsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Notifications /StaticNotifications/StaticNotificationsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Notifications /ToastNotifications/ToastNotificationsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/SwiftUIController.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/PageControls/PageControlsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Shimmers/ShimmersSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/InformerTabs/InformerTabSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/TabsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TagsChips/TagsChipsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/DropDown/DropDownSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/Headers/HeadersSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/Link/LinkSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/Paragraph/ParagraphSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/Separator/SeparatorSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/TextBlocksSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextFields/TextField/Standard/StandardTextFieldSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextFields/TextField/StandardTextFieldsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextFields/TextFieldsSwiftUIView.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Calendar/Horizontal/HorizontalViewController.swift
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/MainViewController.swift
  ExampleiOS/Source/Lifecycle/AppDelegate.swift
  Source/AdmiralSwiftUI/Classes/Components/Views/Calendar/CalendarVerticalView/CalendarVerticalView.swift
  Source/AdmiralUIKit/Classes/Components/Views/Calendar/HorizontalCalendar/CalendarHorizontalView.swift
  Source/AdmiralUIKit/Classes/Components/Views/Calendar/VerticalCalendar/CalendarVerticalView.swift
Labels: enhancement

#154 [BUMP] - 7
  AdmiralSwiftUI.podspec
  AdmiralTheme.podspec
  AdmiralUIKit.podspec
  AdmiralUIResources.podspec
  ExampleiOS/Source/Supporting Files/Info.plist
  Source/AdmiralSwiftUI/Supporting Files/Info.plist
  Source/AdmiralTheme/Supporting Files/Info.plist
  Source/AdmiralUIKit/Supporting Files/Info.plist
  Source/AdmiralUIResources/Supporting Files/Info.plist
  Tests/AdmiralSwiftUITests/Supporting Files/Info.plist
  Tests/AdmiralUIKitTests/Supporting Files/Info.plist
  version.json
Labels: enhancement

#159 [158] - Added pod spec source
  AdmiralSwiftUI.podspec
  AdmiralTheme.podspec
  AdmiralUIKit.podspec
  AdmiralUIResources.podspec
  README.md
Labels: bug

#173 [142] - Fixed Bug with DoubleSlider in UIKit
  Source/AdmiralUIKit/Classes/Components/Controls/Slider/DoubleSilder/DoubleSlider.swift
  Source/AdmiralUIKit/Classes/Components/Views/TextFields/DoubleInputRangeTextField/DoubleInputRangeTextField.swift
Labels: bug

#179 [175] - Segment control UIKit
  ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineSliderTabs/UnderlineSliderTabs.swift
  Source/AdmiralUIKit/Classes/Components/Controls/Tab/SlideTab/UnderlineSliderTab/BaseUnderlineSegmentedControl.swift
Labels: bug
